// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251121024918_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("WebApplication1.Models.GameLevel", b =>
                {
                    b.Property<int>("GameLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GameLevelId");

                    b.ToTable("GameLevels");

                    b.HasData(
                        new
                        {
                            GameLevelId = 1,
                            Description = "Mức độ dễ",
                            Title = "Level 1"
                        },
                        new
                        {
                            GameLevelId = 2,
                            Description = "Mức độ trung bình",
                            Title = "Level 2"
                        },
                        new
                        {
                            GameLevelId = 3,
                            Description = "Mức độ khó",
                            Title = "Level 3"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.LevelResult", b =>
                {
                    b.Property<int>("LevelResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CompletionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameLevelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LevelResultId");

                    b.HasIndex("GameLevelId");

                    b.HasIndex("UserId");

                    b.ToTable("LevelResults");

                    b.HasData(
                        new
                        {
                            LevelResultId = 1,
                            CompletionDate = new DateTime(2025, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameLevelId = 1,
                            Score = 80,
                            UserId = 1
                        },
                        new
                        {
                            LevelResultId = 2,
                            CompletionDate = new DateTime(2025, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameLevelId = 2,
                            Score = 60,
                            UserId = 1
                        },
                        new
                        {
                            LevelResultId = 3,
                            CompletionDate = new DateTime(2025, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameLevelId = 1,
                            Score = 90,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GameLevelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OptionA")
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionB")
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionC")
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionD")
                        .HasColumnType("TEXT");

                    b.HasKey("QuestionId");

                    b.HasIndex("GameLevelId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            QuestionId = 1,
                            Answer = "A",
                            Content = "Question 1 of Level 1?",
                            GameLevelId = 1,
                            OptionA = "A",
                            OptionB = "B",
                            OptionC = "C",
                            OptionD = "D"
                        },
                        new
                        {
                            QuestionId = 2,
                            Answer = "B",
                            Content = "Question 2 of Level 1?",
                            GameLevelId = 1,
                            OptionA = "A",
                            OptionB = "B",
                            OptionC = "C",
                            OptionD = "D"
                        },
                        new
                        {
                            QuestionId = 3,
                            Answer = "C",
                            Content = "Question 1 of Level 2?",
                            GameLevelId = 2,
                            OptionA = "A",
                            OptionB = "B",
                            OptionC = "C",
                            OptionD = "D"
                        },
                        new
                        {
                            QuestionId = 4,
                            Answer = "D",
                            Content = "Question 2 of Level 2?",
                            GameLevelId = 2,
                            OptionA = "A",
                            OptionB = "B",
                            OptionC = "C",
                            OptionD = "D"
                        },
                        new
                        {
                            QuestionId = 5,
                            Answer = "A",
                            Content = "Question 1 of Level 3?",
                            GameLevelId = 3,
                            OptionA = "A",
                            OptionB = "B",
                            OptionC = "C",
                            OptionD = "D"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Region", b =>
                {
                    b.Property<int>("regionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("regionId");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            regionId = 1,
                            Name = "Region1"
                        },
                        new
                        {
                            regionId = 2,
                            Name = "Region2"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Role", b =>
                {
                    b.Property<int>("roleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("roleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            roleId = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            roleId = 2,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("GameLevelId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("linkAvatar")
                        .HasColumnType("TEXT");

                    b.Property<string>("otp")
                        .HasColumnType("TEXT");

                    b.Property<int>("regionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("roleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("userId");

                    b.HasIndex("GameLevelId");

                    b.HasIndex("regionId");

                    b.HasIndex("roleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            userId = 1,
                            Email = "admin@example.com",
                            IsDeleted = false,
                            Password = "",
                            linkAvatar = "avatar1.png",
                            otp = "123456",
                            regionId = 1,
                            roleId = 1,
                            username = "user1"
                        },
                        new
                        {
                            userId = 2,
                            Email = "user@example.com",
                            IsDeleted = false,
                            Password = "",
                            linkAvatar = "avatar2.png",
                            otp = "654321",
                            regionId = 2,
                            roleId = 2,
                            username = "user2"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.LevelResult", b =>
                {
                    b.HasOne("WebApplication1.Models.GameLevel", "GameLevel")
                        .WithMany("LevelResults")
                        .HasForeignKey("GameLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.User", "User")
                        .WithMany("LevelResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameLevel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApplication1.Models.Question", b =>
                {
                    b.HasOne("WebApplication1.Models.GameLevel", "GameLevel")
                        .WithMany("Questions")
                        .HasForeignKey("GameLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameLevel");
                });

            modelBuilder.Entity("WebApplication1.Models.User", b =>
                {
                    b.HasOne("WebApplication1.Models.GameLevel", null)
                        .WithMany("Users")
                        .HasForeignKey("GameLevelId");

                    b.HasOne("WebApplication1.Models.Region", "region")
                        .WithMany("Users")
                        .HasForeignKey("regionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.Role", "role")
                        .WithMany("Users")
                        .HasForeignKey("roleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("region");

                    b.Navigation("role");
                });

            modelBuilder.Entity("WebApplication1.Models.GameLevel", b =>
                {
                    b.Navigation("LevelResults");

                    b.Navigation("Questions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("WebApplication1.Models.Region", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("WebApplication1.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("WebApplication1.Models.User", b =>
                {
                    b.Navigation("LevelResults");
                });
#pragma warning restore 612, 618
        }
    }
}
